# -*- coding: utf-8 -*-
"""IPAM - FABRICA DE GIFS COM EARTH ENGINE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1orM8plKmLIa4qkmPGLY3nvtr5gXwDUd3

# Step 0 - Notebook Presentation

#### This notebook demonstrates how to download images from Earth Engine and generate animated GIFs using those images. The output files are saved to a folder in Google Drive. The notebook uses MapBiomas data collections to create animations for different territorial sections.

<details>
  <summary><strong>Clique para expandir/ocultar os detalhes em português</strong></summary>

  Este notebook demonstra como baixar imagens do Earth Engine e gerar GIFs animados utilizando essas imagens. Os arquivos de saída são salvos em uma pasta no Google Drive. O notebook utiliza as coleções de dados do MapBiomas para criar animações em diferentes recortes territoriais.

  No **passo 1** será solicitado a autorização para logar e conectar ao Google Drive e ao Google Earth Engine. Certifique-se de colocar um projeto que esteja sincronizado com sua conta no Google Earth Engine.

  No **passo 2** é necessário indicar o nome da pasta na raiz do seu google drive, pode ser um atalho, se o nome indicado não existir, uma pasta com esse nome é criada.

  No **passo 3** estão os mapas de entrada em raster, e estão divididos existem três células:
  - **3a:** Conjunto de variáveis contendo `eeObject`'s, imagens ou mapas de interesse.
  - **3b:** Dicionário com os parâmetros de visualização, para os mapas de interesse.
  - **3c:** Lista de objetos de referência, que entram no loop, de produtos salvos no GDrive. Para expandir ou reduzir esse loop, basta comentar ou remover os objetos de forma individual nesta célula 2c.

  No **passo 4** estão o conjunto de mapas em vetor, que serão utilizados no loop para multiplicar os mapas em função de recortes geográficos.

  No **passo 5** estão as principais funções desenvolvidas para esta rotina, aqui está o que pode ter de interessante para outros desenvolvedores investigarem para reprogramar ou adaptar os trechos em outros códigos.

  No **passo 6** ocorre o loop que gera e salva no Google Drive os frames no Google Drive, em função das listas disponíveis nos passos 3c e 4.

  No **passo 7** ocorre um segundo loop que dispara e salva os GIFs e quadros no Google Drive, em função das listas disponíveis nos passos 3c e 4.

</details>

<details>
  <summary><strong>Click to expand/collapse details in English</strong></summary>

  This notebook demonstrates how to download images from Earth Engine and generate animated GIFs using those images. The output files are saved to a folder in Google Drive. The notebook uses MapBiomas data collections to create animations for different territorial sections.

  In **step 1**, you will be asked to authorize logging in and connecting to Google Drive and Google Earth Engine. Make sure to set up a project that is synchronized with your Google Earth Engine account.

  In **step 2**, you need to specify the name of the folder in the root of your Google Drive, which can be a shortcut. If the specified name does not exist, a folder with that name will be created.

  In **step 3**, the input maps are in raster format and are divided into three cells:
  - **3a:** A set of variables containing `eeObject`s, images, or maps of interest.
  - **3b:** A dictionary with the visualization parameters for the maps of interest.
  - **3c:** A list of reference objects that enter the loop and are saved to Google Drive. To expand or reduce this loop, simply comment or remove the objects individually in this cell 2c.

  In **step 4**, the set of vector maps that will be used in the loop to multiply the maps based on geographical cuts is configured.

  In **step 5**, the main functions developed for this routine are included. These functions might be interesting for other developers to investigate for reprogramming or adapting the code snippets in other projects.

  In **step 6**, the loop that generates and saves the frames in Google Drive occurs, based on the lists available in steps 3c and 4.

  In **step 7**, a second loop is executed that triggers and saves the GIFs and frames in Google Drive, based on the lists available in steps 3c and 4.

</details>

<details>
  <summary><strong>Haga clic para expandir/ocultar detalles en español</strong></summary>

  Este cuaderno demuestra cómo descargar imágenes de Earth Engine y generar GIFs animados utilizando esas imágenes. Los archivos de salida se guardan en una carpeta en Google Drive. El cuaderno utiliza colecciones de datos de MapBiomas para crear animaciones en diferentes secciones territoriales.


  En el **paso 1** se te pedirá que autorices el inicio de sesión y la conexión a Google Drive y Google Earth Engine. Asegúrate de configurar un proyecto que esté sincronizado con tu cuenta de Google Earth Engine.

  En el **paso 2** es necesario indicar el nombre de la carpeta en la raíz de tu Google Drive, puede ser un acceso directo. Si el nombre indicado no existe, se creará una carpeta con ese nombre.

  En el **paso 3** los mapas de entrada están en formato raster y se dividen en tres celdas:
  - **3a:** Conjunto de variables que contienen `eeObject`s, imágenes o mapas de interés.
  - **3b:** Diccionario con los parámetros de visualización para los mapas de interés.
  - **3c:** Lista de objetos de referencia que ingresan al bucle y se guardan en Google Drive. Para expandir o reducir este bucle, simplemente comenta o elimina los objetos individualmente en esta celda 2c.

  En el **paso 4** se configura el conjunto de mapas vectoriales que se utilizarán en el bucle para multiplicar los mapas en función de los recortes geográficos.

  En el **paso 5** se incluyen las funciones principales desarrolladas para esta rutina. Estas funciones pueden ser interesantes para que otros desarrolladores las investiguen para reprogramar o adaptar los fragmentos de código en otros proyectos.

  En el **paso 6** ocurre el bucle que genera y guarda los frames en Google Drive, en función de las listas disponibles en los pasos 3c y 4.

  En el **paso 7** se ejecuta un segundo bucle que dispara y guarda los GIFs y cuadros en Google Drive, en función de las listas disponibles en los pasos 3c y 4.

</details>

<details>
  <summary><strong>Klik untuk memperluas/menciutkan detail dalam bahasa Indonesia</strong></summary>

  Notebook ini menunjukkan cara mengunduh gambar dari Earth Engine dan menghasilkan GIF animasi menggunakan gambar-gambar tersebut. File keluaran disimpan di folder di Google Drive. Notebook ini menggunakan koleksi data MapBiomas untuk membuat animasi untuk berbagai wilayah teritorial.


  Pada **langkah 1** Anda akan diminta untuk mengizinkan login dan menghubungkan ke Google Drive dan Google Earth Engine. Pastikan untuk menyiapkan proyek yang disinkronkan dengan akun Google Earth Engine Anda.

  Pada **langkah 2** perlu ditentukan nama folder di root Google Drive Anda, yang bisa berupa pintasan. Jika nama yang ditentukan tidak ada, maka folder dengan nama tersebut akan dibuat.

  Pada **langkah 3** peta masukan dalam format raster dan dibagi menjadi tiga sel:
  - **3a:** Satu set variabel yang berisi `eeObject`, gambar, atau peta yang menarik.
  - **3b:** Kamus dengan parameter visualisasi untuk peta yang menarik.
  - **3c:** Daftar objek referensi yang masuk ke dalam loop dan disimpan ke Google Drive. Untuk memperluas atau mengurangi loop ini, cukup komentari atau hapus objek satu per satu di sel ini 2c.

  Pada **langkah 4** kumpulan peta vektor yang akan digunakan dalam loop untuk mengalikan peta berdasarkan pemotongan geografis dikonfigurasi.

  Pada **langkah 5** fungsi utama yang dikembangkan untuk rutinitas ini disertakan. Fungsi-fungsi ini mungkin menarik bagi pengembang lain untuk diselidiki untuk memprogram ulang atau menyesuaikan potongan kode dalam proyek lain.

  Pada **langkah 6** terjadi loop yang menghasilkan dan menyimpan frame di Google Drive, berdasarkan daftar yang tersedia di langkah 3c dan 4.

  Pada **langkah 7** loop kedua dieksekusi yang memicu dan menyimpan GIF dan frame di Google Drive, berdasarkan daftar yang tersedia di langkah 3c dan 4.

</details>

  ## Examples
  #### Fogo Anual na Indonésia
  ---
  <img src="https://drive.google.com/uc?id=11CBg5X2XPdLTmnglMLTY92JLyZ2k6qH5" alt="Fogo Anual na Indonésia" style="max-width:100%; height:auto;">

  #### Recorrência de Fogo na Indonésia
  ---
  <img src="https://drive.google.com/uc?id=1O7adHQ1zV4pCoGLGYX5sUf8hvIw3gGtH" alt="Recorrência de Fogo na Indonésia" style="max-width:100%; height:auto;">

# Step 1 - Authorization and Connection to Google Drive and Google Earth Engine

In this step, you will authorize the notebook to access your Google Drive and Google Earth Engine account. This step is essential for saving outputs and interacting with datasets stored in your Google Drive and Earth Engine. Make sure to select the correct Google account that is synchronized with the project you are working on.

The notebook will prompt you to log in and grant the necessary permissions. Once you have successfully logged in, the notebook will establish the required connections to your Google Drive and Google Earth Engine.
"""

# step 1: This code requests authorization to access Google Drive and Google Earth Engine
# Make sure you are logged into the correct Google account.

# Install required libraries
!pip install earthengine-api
!pip install imageio[pyav]
!pip install IPython
!pip install Pillow
!pip install opencv-python-headless

# import the libraries
import ee
import requests
import imageio
import os
import time
from PIL import Image as PILImage, ImageDraw, ImageFont
from google.colab import drive
from IPython.display import Image, display
import matplotlib.pyplot as plt
import cv2
import numpy as np
import concurrent.futures

# Authenticate and Initialize Earth Engine
ee.Authenticate()
ee.Initialize(project='workspace-ipam')  # The project depends on the authenticated Earth Engine account

# Mount Google Drive in Colab
drive.mount('/content/drive')

"""# Step 2 - Google Drive Directory Setup

In this step, you need to set up the directory in Google Drive where the generated files will be saved. You can specify the name of the folder in the root of your Google Drive, and if the folder does not exist, it will be created automatically. Ensure that the folder name is clear and easily identifiable, as it will be used in the subsequent steps for storing outputs.
  
"""

# step 2: Set up the Google Drive directory where outputs will be saved.
# If the specified directory doesn't exist, it will be created automatically.

# Define the folder name in Google Drive
main_path = '/content/drive/MyDrive/IPAM FRAMES AND GIFS/'

# Create the directory if it doesn't exist
if not os.path.exists(main_path):
    os.makedirs(main_path)
    print(f"Created main directory: {main_path}")
else:
    print(f"Main directory already exists: {main_path}")

"""# Step 3 - Setup of Input Raster Maps

In this step, you will configure the input raster maps that will be used in the analysis. This step is divided into three substeps:

## 3a - Define Variables Containing `eeObject`s
In this substep, you will define the variables that contain the `eeObject`s, which represent the images or maps of interest.

## 3b - Set Visualization Parameters
Here, you will define the visualization parameters for the maps of interest, such as color palettes, min and max values.

## 3c - List Reference Objects for Loop Processing
Finally, you will list the reference objects that will enter the processing loop. These objects will be used to generate outputs and can be adjusted by adding or removing items from the list.

"""

#  step 3a: - Define the `eeObject` variables that represent the images or maps of interest.
# Example: Defining an Earth Engine image collections for MapBiomas data

# Brasil MapBiomas Fire collection 3
accumulated_burned_coverage = ee.Image("projects/mapbiomas-public/assets/brazil/fire/collection3/mapbiomas_fire_collection3_accumulated_burned_coverage_v1")
accumulated_burned = ee.Image("projects/mapbiomas-public/assets/brazil/fire/collection3/mapbiomas_fire_collection3_accumulated_burned_v1")
annual_burned_coverage = ee.Image("projects/mapbiomas-public/assets/brazil/fire/collection3/mapbiomas_fire_collection3_annual_burned_coverage_v1")
annual_burned = ee.Image("projects/mapbiomas-public/assets/brazil/fire/collection3/mapbiomas_fire_collection3_annual_burned_v1")
# fire_frequency_coverage = ee.Image("projects/mapbiomas-public/assets/brazil/fire/collection3/mapbiomas_fire_collection3_fire_frequency_coverage_v1")
fire_frequency = ee.Image("projects/mapbiomas-public/assets/brazil/fire/collection3/mapbiomas_fire_collection3_fire_frequency_v1")
# monthly_burned_coverage = ee.Image("projects/mapbiomas-public/assets/brazil/fire/collection3/mapbiomas_fire_collection3_monthly_burned_coverage_v1")
monthly_burned = ee.Image("projects/mapbiomas-public/assets/brazil/fire/collection3/mapbiomas_fire_collection3_monthly_burned_v1")
scar_size_range = ee.Image('projects/mapbiomas-public/assets/brazil/fire/collection3/mapbiomas_fire_collection3_annual_burned_scar_size_range_v1')
year_last_fire = ee.Image('projects/mapbiomas-public/assets/brazil/fire/collection3/mapbiomas_fire_collection3_year_last_fire_v1')
time_after_fire = ee.Image('projects/mapbiomas-workspace/FOGO_COL3/2-Subprodutos/mapbiomas-fire-collection3-time-after-fire-v1')
time_before_fire = ee.Image('projects/mapbiomas-workspace/FOGO_COL3/2-Subprodutos/mapbiomas-fire-collection3-time-before-fire-v1')
year_next_fire = ee.Image('projects/mapbiomas-workspace/FOGO_COL3/2-Subprodutos/mapbiomas-fire-collection3-year-next-fire-v1')

# Paraguay MapBiomas Fogo collection 1
paraguay_accumulated_burned_coverage = ee.Image("projects/mapbiomas-paraguay/assets/FIRE/COLLECTION1/FINAL_PRODUCTS/mapbiomas_paraguay_fire_collection1_accumulated_burned_coverage_v1")
paraguay_accumulated_burned = ee.Image("projects/mapbiomas-paraguay/assets/FIRE/COLLECTION1/FINAL_PRODUCTS/mapbiomas_paraguay_fire_collection1_accumulated_burned_v1")
paraguay_annual_burned_coverage = ee.Image("projects/mapbiomas-public/assets/paraguay/fire/collection1/mapbiomas_paraguay_fire_collection1_annual_burned_coverage_v1")
paraguay_annual_burned = ee.Image("projects/mapbiomas-paraguay/assets/FIRE/COLLECTION1/FINAL_PRODUCTS/mapbiomas_paraguay_fire_collection1_annual_burned_v1")
paraguay_fire_frequency = ee.Image("projects/mapbiomas-paraguay/assets/FIRE/COLLECTION1/FINAL_PRODUCTS/mapbiomas_paraguay_fire_collection1_frequency_burned_v1")
paraguay_monthly_burned = ee.Image("projects/mapbiomas-paraguay/assets/FIRE/COLLECTION1/FINAL_PRODUCTS/mapbiomas_paraguay_fire_collection1_monthly_burned_v1")

# Brasil MapBiomas Landuse and landcover collection 9
integration = ee.Image('projects/mapbiomas-public/assets/brazil/lulc/collection9/mapbiomas_collection90_integration_v1')
deforestation_secondary_vegetation_accumulated = ee.Image('projects/mapbiomas-public/assets/brazil/lulc/collection9/mapbiomas_collection90_deforestation_secondary_vegetation_accumulated_v1')
deforestation_secondary_vegetation = ee.Image('projects/mapbiomas-public/assets/brazil/lulc/collection9/mapbiomas_collection90_deforestation_secondary_vegetation_v1').divide(100).int8()
irrigated_agriculture = ee.Image('projects/mapbiomas-public/assets/brazil/lulc/collection9/mapbiomas_collection90_irrigated_agriculture_v1')
mined_substance = ee.Image('projects/mapbiomas-public/assets/brazil/lulc/collection9/mapbiomas_collection90_mined_substance_v1')
pasture_quality = ee.Image('projects/mapbiomas-public/assets/brazil/lulc/collection9/mapbiomas_collection90_pasture_quality_v1')
quality = ee.Image('projects/mapbiomas-public/assets/brazil/lulc/collection9/mapbiomas_collection90_quality_v1')
secondary_vegetation_age = ee.Image('projects/mapbiomas-public/assets/brazil/lulc/collection9/mapbiomas_collection90_secondary_vegetation_age_v1')
# transitions = ee.Image('projects/mapbiomas-public/assets/brazil/lulc/collection9/mapbiomas_collection90_transitions_v1')

integration_COL10 = ee.Image('projects/mapbiomas-public/assets/brazil/lulc/collection10/mapbiomas_brazil_collection10_integration_v2')
deforestation_secondary_vegetation_COL10 = ee.Image('projects/mapbiomas-public/assets/brazil/lulc/collection10/mapbiomas_brazil_collection10_deforestation_secondary_vegetation_v2')
irrigated_agriculture_COL10 = ee.Image('projects/mapbiomas-public/assets/brazil/lulc/collection10/mapbiomas_brazil_collection10_agriculture_irrigation_systems_v2')
mined_substance_COL10 = ee.Image('projects/mapbiomas-public/assets/brazil/lulc/collection10/mapbiomas_brazil_collection10_mining_substances_v3')
pasture_quality_COL10 = ee.Image('projects/mapbiomas-public/assets/brazil/lulc/collection10/mapbiomas_brazil_collection10_pasture_vigor_v1')


# Brasil MapBiomas Soil
soc = ee.ImageCollection('projects/mapbiomas-workspace/SOLOS/PRODUTOS_BETA/soil_organic_carbon-0_30_cm_t_ha-beta_2_1').mosaic()
soc = soc.updateMask(soc.neq(-2))

# Brasil MapBiomas Degradation
# Criação das variáveis para cada produto
# --- base auxiliar
landcover_base = ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/reference_native/reference_col9_v1')

# --- base auxiliar
degradation_bordasArea = landcover_base.where(landcover_base.gte(1), 9)\
    .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/edge_area/edge_1000m_col9_v1').gt(1).multiply(8))\
    .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/edge_area/edge_600m_col9_v1').gt(1).multiply(7))\
    .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/edge_area/edge_300m_col9_v1').gt(1).multiply(6))\
    .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/edge_area/edge_150m_col9_v1').gt(1).multiply(5))\
    .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/edge_area/edge_120m_col9_v1').gt(1).multiply(4))\
    .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/edge_area/edge_90m_col9_v1').gt(1).multiply(3))\
    .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/edge_area/edge_60m_col9_v1').gt(1).multiply(2))\
    .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/edge_area/edge_30m_col9_v1').gt(1).multiply(1))

degradation_fragmentSize = landcover_base.where(landcover_base.gte(1), 7)\
    .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/patch_size/size_75ha_col9_v1').gt(1).multiply(6))\
    .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/patch_size/size_50ha_col9_v1').gt(1).multiply(5))\
    .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/patch_size/size_25ha_col9_v1').gt(1).multiply(4))\
    .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/patch_size/size_10ha_col9_v1').gt(1).multiply(3))\
    .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/patch_size/size_5ha_col9_v1').gt(1).multiply(2))\
    .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/patch_size/size_3ha_col9_v1').gt(1).multiply(1))

degradation_distances100ha = landcover_base.multiply(0)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/BR_Distance/natural_mask_maior100ha_85_234'), 10)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag50_dist05k_100_v7_85_23'), 2)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag25_dist05k_100_v7_85_23'), 3)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag50_dist10k_100_v7_85_23'), 5)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag25_dist10k_100_v7_85_23'), 6)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag50_dist20k_100_v7_85_23'), 8)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag25_dist20k_100_v7_85_23'), 9)

degradation_distances500ha = landcover_base.multiply(0)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/BR_Distance/natural_mask_maior500ha_85_234'), 11)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag100_dist05k_500_v7_85_23'), 1)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag50_dist05k_500_v7_85_23'), 2)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag25_dist05k_500_v7_85_23'), 3)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag100_dist10k_500_v7_85_23'), 4)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag50_dist10k_500_v7_85_23'), 5)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag25_dist10k_500_v7_85_23'), 6)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag50_dist20k_500_v7_85_23'), 8)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag25_dist20k_500_v7_85_23'), 9)

degradation_distances1000ha = landcover_base.multiply(0)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/BR_Distance/natural_mask_maior1000ha_85_234'), 12)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag100_dist05k_1000_v7_85_23'), 1)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag50_dist05k_1000_v7_85_23'), 2)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag25_dist05k_1000_v7_85_23'), 3)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag100_dist10k_1000_v7_85_23'), 4)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag50_dist10k_1000_v7_85_23'), 5)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag25_dist10k_1000_v7_85_23'), 6)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag100_dist20k_1000_v7_85_23'), 7)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag50_dist20k_1000_v7_85_23'), 8)\
    .where(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/ISOLATION_col9_v2/nat_uso_frag25_dist20k_1000_v7_85_23'), 9)

# Bordas de 30 a 100m
degradation_edge_area = landcover_base.where(landcover_base.gte(1), 9)\
  .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/edge_area/edge_1000m_col9_v1').gt(1).multiply(8))\
  .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/edge_area/edge_600m_col9_v1').gt(1).multiply(7))\
  .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/edge_area/edge_300m_col9_v1').gt(1).multiply(6))\
  .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/edge_area/edge_150m_col9_v1').gt(1).multiply(5))\
  .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/edge_area/edge_120m_col9_v1').gt(1).multiply(4))\
  .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/edge_area/edge_90m_col9_v1').gt(1).multiply(3))\
  .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/edge_area/edge_60m_col9_v1').gt(1).multiply(2))\
  .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/edge_area/edge_30m_col9_v1').gt(1).multiply(1))

# Tamanho dos Fragmentos (≤ 3 a 75 ha)
degradation_patch_size = landcover_base.multiply(0)\
  .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/patch_size/size_75ha_col9_v1').gt(1).multiply(6))\
  .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/patch_size/size_50ha_col9_v1').gt(1).multiply(5))\
  .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/patch_size/size_25ha_col9_v1').gt(1).multiply(4))\
  .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/patch_size/size_10ha_col9_v1').gt(1).multiply(3))\
  .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/patch_size/size_5ha_col9_v1').gt(1).multiply(2))\
  .blend(ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/patch_size/size_3ha_col9_v1').gt(1).multiply(1))

# Cobertura da Vegetação Secundária
degradation_secondary_vegetation_coverage = ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/secondary_vegetation/secondary_vegetation_age_col9_v1').mod(100).int8()

# Idade da Vegetação Secundária
degradation_secondary_vegetation_age = ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/secondary_vegetation/secondary_vegetation_age_col9_v1').divide(100).int8()

# Frequência do Fogo
degradation_fire_frequency = ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/fire/recurrence_col9_v1').divide(100).int8()

# Idade do Fogo
degradation_fire_age = ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/fire/recurrence_col9_v1').multiply(0).slice(1).add(
    ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/fire/age_col9_v1').divide(100).int8()
)

# Cobertura Queimada Acumulada
degradation_accumulated_burned_coverage = ee.Image('projects/mapbiomas-workspace/DEGRADACAO/COLECAO/BETA/PROCESS/fire/recurrence_col9_v1').mod(100).int8()

# Cobertura Queimada do Monitor do Fogo
# Coleção de imagens monitor_collection deve ser definida previamente
monitor_collection = ee.ImageCollection('projects/mapbiomas-workspace/FOGO/MONITORAMENTO/collection-fire-monthly-sentinel2-v3').filter(ee.Filter.eq('year',2024))
def map_set_year_month(image):
  image = image.set({'year_month':image.getNumber('year').multiply(100).add(image.getNumber('month')).int()})
  return  image.int8()

# Função para iterar sobre os anos e criar a imagem anual
def iterate_function_adapt (current, previous):
    year_month = ee.Number(current).int()
    new_img = monitor_collection_adapt.filter(ee.Filter.eq('year_month', year_month)).mosaic().rename(ee.String(year_month))
    return ee.Image(previous).addBands(new_img)

def iterate_function_adapt_accumulated (current, previous):
    year_month = ee.Number(current).int()
    new_img = monitor_collection_adapt.filter(ee.Filter.lte('year_month', year_month)).mosaic().rename(ee.String(year_month))
    return ee.Image(previous).addBands(new_img)

def iterate_function_adapt_accumulated_coverage (current, previous):
    year_month = ee.Number(current).int()
    new_img = monitor_collection_adapt.filter(ee.Filter.lte('year_month', year_month)).mosaic().rename(ee.String(year_month)).multiply(integration.select('classification_2023'))
    return ee.Image(previous).addBands(new_img)

def iterate_function_adapt_coverage (current, previous):
    year_month = ee.Number(current).int()
    new_img = monitor_collection_adapt.filter(ee.Filter.eq('year_month', year_month)).mosaic().rename(ee.String(year_month)).multiply(integration.select('classification_2023'))
    return ee.Image(previous).addBands(new_img)

monitor_collection_adapt = monitor_collection.map(map_set_year_month)
year_month = ee.List(monitor_collection_adapt.aggregate_array('year_month').distinct().sort())
monitor_monthly = ee.Image(year_month.iterate(iterate_function_adapt, ee.Image().select()))

monitor_monthly_accumulated = ee.Image(year_month.iterate(iterate_function_adapt_accumulated, ee.Image().select()))

monitor_monthly_accumulated_coverage = ee.Image(year_month.iterate(iterate_function_adapt_accumulated_coverage, ee.Image().select()))
monitor_monthly_coverage = ee.Image(year_month.iterate(iterate_function_adapt_coverage, ee.Image().select()))

#  step 3b: - Set the visualization parameters for the maps of interest.

# Example: Defining visualization parameters for land cover
visParams = {
  "fire":{
    "min":0,
    "max":1,
    "palette":[
      "fdfdfd","800000"
    ]
  },
  "monthly":{
    'min':0,
    'max':12,
    "palette":[
      "fdfdfd","55E3E6","27d3c3","00c29b","19b06f","08cf26","53e300","dbc900","ff8800","ff3c00","df2a02","c01702","a10000",
    ]
  },
  "frequency":{
    'min':0,
    'max':11,
    "palette":[
      "fdfdfd","faf3cd","fce68d","f9de44","f6d51d","e9bc1c","cc8715","b76011","9f360b","810004","4b0709","080202",
    ]
  },
  "frequency_paraguay":{
    'min':0,
    'max':26,
    "palette":[
      'ffffff','#faf3cd','#fced97','#fae154','#f8d823','#eec41d','#e1ae1a','#d49616','#ca8315','#bd6c12','#b25810','#a6420d','#9a2b0a','#8f1807','#800004','#6d0306','#5d0407','#4b0709','#410708','#370608','#2e0506','#240505','#1b0404','#130303','#0b0203','#040101'
    ]
  },
  "lulc": {
    "min":0,
    "max":62,
    "palette":[
        '#ffffff','#32a65e','#32a65e','#1f8d49','#7dc975','#04381d','#026975','#000000','#000000','#7a6c00','#ad975a','#519799','#d6bc74','#d89f5c','#FFFFB2','#edde8e','#000000','#000000','#f5b3c8','#C27BA0','#db7093','#ffefc3','#db4d4f','#ffa07a','#d4271e','#db4d4f','#0000FF','#000000','#000000','#ffaa5f','#9c0027','#091077','#fc8114','#2532e4','#93dfe6','#9065d0','#d082de','#000000','#000000','#f5b3c8','#c71585','#f54ca9','#cca0d4','#dbd26b','#807a40','#e04cfa','#d68fe2','#9932cc','#e6ccff','#02d659','#ad5100','#000000','#000000','#000000','#000000','#000000','#000000','#CC66FF','#FF6666','#006400','#8d9e8b','#f5d5d5','#ff69b4'
    ]
  },
  'scar_size_range': {
    'min':0,
    'max':10,
    'palette': ['ffffff', 'd0ae35', 'd08d29', 'cc6c28', 'c2482e', 'b31e35', '931f28', '741e1d', '571a14', '3c150b', '240d00'],
  },
  'year_last_fire': {
    'min': 1985,
    'max': 2022,
    'palette': ['ffffff','000079', '00147d', '00227f', '002d81', '003781', '004080', '004c7b', '00557f', '005e86', '00688c','007292', '007d96', '008998', '0a9294', '26A09E', '41ACA6', '5DB9AD', '78C5B5', '94D2BD', '9FBD98','AAA772', 'B4924D', 'BF7C27', 'CA6702', 'C45905', 'BF4B08', 'B93C0C', 'B42E0F', 'AE2012', 'AA2016','A6211A', 'A3211E', '9F2222', '9B2226', '961B1E', '901417', '8B0E0F', '850708', '800000', '800000'],
  },
  'year_next_fire': {
    'min': 1986,
    'max': 2023,
    'palette': ['ffffff','000079', '00147d', '00227f', '002d81', '003781', '004080', '004c7b', '00557f', '005e86', '00688c','007292', '007d96', '008998', '0a9294', '26A09E', '41ACA6', '5DB9AD', '78C5B5', '94D2BD', '9FBD98','AAA772', 'B4924D', 'BF7C27', 'CA6702', 'C45905', 'BF4B08', 'B93C0C', 'B42E0F', 'AE2012', 'AA2016','A6211A', 'A3211E', '9F2222', '9B2226', '961B1E', '901417', '8B0E0F', '850708', '800000', '800000'],
  },
  'fire_age': {
    'min': 0,
    'max': 39,
    'palette': ['ffffff','800000', '800000', '850708', '8B0E0F', '901417', '961B1E', '9B2226', '9F2222', 'A3211E', 'A6211A', 'AA2016', 'AE2012', 'B42E0F', 'B93C0C', 'BF4B08', 'C45905', 'CA6702', 'BF7C27', 'B4924D', 'AAA772', '9FBD98', '94D2BD', '78C5B5', '5DB9AD', '41ACA6', '26A09E', '0A9294', '008998', '007D96', '007292', '00688C', '005E86', '00557F', '004C7B', '004080', '003781', '002D81', '00227F', '00147D', '000079'],
  },
  "def_seco":{
    "min":0,
    "max":7,
    "palette":['ffffff','fff6bf','127622','56d117','ea1c1c','6fc4b7','ffb66c','8c8c8c'],
  },
  "soc":{
    'min':-1,
    'max':80,
    'palette': ['ffffff','ffffe5', 'fff7bc', 'fee391', 'fec44f', 'fe9929', 'ec7014', 'cc4c02', '993404', '662506'],
  },
    "bordasArea": {
      "min": 0,
      "max": 9,
      "palette": ['#55604B', '#FF0001', '#32CD32', '#19B06F', '#6FA8DC', '#0B5394', '#A64D79', '#F54CA9', '#55604B']
    },
  "distances": {
      'min': 0,
      'max': 12,
      'palette': ['#55604B', '#000080', '#0000ff', '#8080ff', '#008000', '#00ff00', '#80ff80','#800000', '#ff0000', '#FF8080', '#55604B', '#55604B', '#55604B']
    },
  "edge_area": {
      'min': 0,
      'max': 9,
      'palette': ['#55604B', '#FF0001', '#32CD32', '#19B06F', '#6FA8DC', '#0B5394', '#A64D79', '#F54CA9', '#55604B']
    },
    "secondary_vegetation_age": {
        'min': 0,
        'max': 39,
        'palette': ['ffffff',"505050","f3f6c2","f1f69a","eff672","eef64a","ecf622","d7f622","c2f622","adf622","93f622","79f622","6ff622","62f625","58f627","4ef629","40f62b","36f62d","2cf62f","22f631","22e72d","22dd2a","22c925","23b520","23ab1d","23a11b","239718","238814","237e12","247510","246b0d","24660c","24630b","255808"]
    },
    "patch_size": {
      'min': 0,
      'max': 7,
      'palette': ['#A9A9A9', '#E50C08', '#FFAA5F', '#32CD32', '#19B06F', '#6FA8DC', '#0B5394', '#A9A9A9']
    }
}

#  step 3c: - List the reference objects that wrocessed in the loop.
# Adjust the list as needed by adding or removing objects.

def only_coverage (list,image,alternative_landcover):
  landcover_observed = alternative_landcover
  image_container = image.multiply(0);
  for i in list:
    image_container = image_container.where(landcover_observed.eq(i).selfMask(),image)

  return ee.Image(image_container).selfMask()

datasets = [
  # {
  #   'type': 'image',
  #   'name': 'Monitor do Fogo 2024 cobertura mensal',
  #   'eeObject': monitor_monthly_coverage,
  #   'visParams': visParams["lulc"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Monitor do Fogo 2024 coberutra acumulada',
  #   'eeObject': monitor_monthly_accumulated_coverage,
  #   'visParams': visParams["lulc"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Água collection 9',
  #   'eeObject': integration.eq(33).multiply(33).selfMask(),
  #   'visParams': visParams["lulc"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Monitor do Fogo 2024 mensal',
  #   'eeObject': monitor_monthly,
  #   'visParams': visParams["fire"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Monitor 2024 acumulado',
  #   'eeObject': monitor_monthly_accumulated,
  #   'visParams': visParams["fire"]
  # },


  # {
  #   'type': 'image',
  #   'name': 'Soil Stock Carbon',
  #   'eeObject': soc,
  #   'visParams': visParams["soc"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Deforestation secondary',
  #   'eeObject': deforestation_secondary_vegetation,
  #   'visParams': visParams["def_seco"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'mapbiomas_col9 lulc',
  #   'eeObject': integration,
  #   'visParams': visParams["lulc"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'mapbiomas_col10 lulc',
  #   'eeObject': integration_COL10,
  #   'visParams': visParams["lulc"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'mapbiomas_col10 Vegetation primary and secondary',
  #   'eeObject': deforestation_secondary_vegetation_COL10.multiply(0).where(deforestation_secondary_vegetation_COL10.eq(2),2).where(deforestation_secondary_vegetation_COL10.eq(3),3).selfMask(),
  #   'visParams': visParams["def_seco"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'mapbiomas_col10 Deforestation primary and secondary',
  #   'eeObject': deforestation_secondary_vegetation_COL10.multiply(0).where(deforestation_secondary_vegetation_COL10.eq(4),4).where(deforestation_secondary_vegetation_COL10.eq(6),6).selfMask(),
  #   'visParams': visParams["def_seco"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Annual burned',
  #   'eeObject': annual_burned,
  #   'visParams': visParams["fire"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Annual burned coverage',
  #   'eeObject': annual_burned_coverage,
  #   'visParams': visParams["lulc"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Monthly burned',
  #   'eeObject': monthly_burned,
  #   'visParams': visParams["monthly"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Fire frequency',
  #   'eeObject': fire_frequency.slice(0,39),
  #   'visParams':visParams["frequency"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Accumulated burned coverage',
  #   'eeObject': accumulated_burned_coverage.slice(0,39),
  #   'visParams': visParams["lulc"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Accumulated burned',
  #   'eeObject': accumulated_burned.slice(0,39),
  #   'visParams': visParams["fire"]
  # },





  {
    'type': 'image',
    'name': 'Paraguay Annual burned',
    'eeObject': paraguay_annual_burned,
    'visParams': visParams["fire"]
  },
  {
    'type': 'image',
    'name': 'Paraguay Annual burned coverage',
    'eeObject': paraguay_annual_burned_coverage,
    'visParams': visParams["lulc"]
  },
  {
    'type': 'image',
    'name': 'Paraguay Monthly burned',
    'eeObject': paraguay_monthly_burned,
    'visParams': visParams["monthly"]
  },
  {
    'type': 'image',
    'name': 'Paraguay Fire frequency',
    'eeObject': paraguay_fire_frequency.slice(0,26),
    'visParams':visParams["frequency_paraguay"]
  },
  {
    'type': 'image',
    'name': 'Paraguay Accumulated burned coverage',
    'eeObject': paraguay_accumulated_burned_coverage.slice(0,26),
    'visParams': visParams["lulc"]
  },
  {
    'type': 'image',
    'name': 'Paraguay Accumulated burned',
    'eeObject': paraguay_accumulated_burned.slice(0,26),
    'visParams': visParams["fire"]
  },


  # {
  #   'type': 'image',
  #   'name': 'Year last fire',
  #   'eeObject': year_last_fire,
  #   'visParams': visParams["year_last_fire"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Scar size range',
  #   'eeObject': scar_size_range,
  #   'visParams': visParams["scar_size_range"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Time after fire',
  #   'eeObject': time_after_fire,
  #   'visParams': visParams["fire_age"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Time before fire',
  #   'eeObject': time_before_fire,
  #   'visParams': visParams["fire_age"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Year next fire',
  #   'eeObject': year_next_fire,
  #   'visParams': visParams["year_next_fire"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Degradation - Distance 100ha',
  #   'eeObject': degradation_distances100ha,
  #   'visParams': visParams["distances"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Degradation - Distance 500ha',
  #   'eeObject': degradation_distances500ha,
  #   'visParams': visParams["distances"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Degradation - Distance 1000ha',
  #   'eeObject': degradation_distances1000ha,
  #   'visParams': visParams["distances"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Degradation col 9 - Edge Area (30-100m)',
  #   'eeObject': degradation_edge_area,
  #   'visParams': visParams["edge_area"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Degradation col 9 - Patch Size (≤ 3 a 75 ha)',
  #   'eeObject': degradation_patch_size,
  #   'visParams': visParams["patch_size"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Degradation col 9 - Secondary Vegetation Coverage',
  #   'eeObject': degradation_secondary_vegetation_coverage,
  #   'visParams': visParams["lulc"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Degradation col 9 - Secondary Vegetation Age',
  #   'eeObject': degradation_secondary_vegetation_age,
  #   'visParams': visParams["secondary_vegetation_age"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Degradation col 9 - Fire Frequency',
  #   'eeObject': degradation_fire_frequency,
  #   'visParams': visParams["frequency"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Degradation col 9 - Fire Age',
  #   'eeObject': degradation_fire_age,
  #   'visParams': visParams["fire_age"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Degradation col 9 - Accumulated Burned Coverage',
  #   'eeObject': degradation_accumulated_burned_coverage,
  #   'visParams': visParams["lulc"]
  # }
  # {
  #   'type': 'image',
  #   'name': 'Degradation col 9 Forests - Edge Area (30-100m)',
  #   'eeObject': only_coverage([3,5,6],degradation_edge_area,landcover_base),
  #   'visParams': visParams["edge_area"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Degradation col 9 Forests - Patch Size (≤ 3 a 75 ha)',
  #   'eeObject': only_coverage([3,5,6],degradation_patch_size,landcover_base),
  #   'visParams': visParams["patch_size"]
  # },
  # {
  #  'type': 'image',
  #  'name': 'Degradation col 9 Forests - Distance 1000ha',
  #  'eeObject': only_coverage([3,5,6],degradation_distances1000ha,landcover_base),
  #  'visParams': visParams["distances"]
  # },
  # {
  #  'type': 'image',
  #  'name': 'Degradation col 9 Forests - Distance 100ha',
  #  'eeObject': only_coverage([3,5,6],degradation_distances100ha,landcover_base),
  #  'visParams': visParams["distances"]
  # },
  # {
  #  'type': 'image',
  #  'name': 'Degradation col 9 Forests - Distance 500ha',
  #  'eeObject': only_coverage([3,5,6],degradation_distances500ha,landcover_base),
  #  'visParams': visParams["distances"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Degradation col 9 Forests - Secondary Vegetation Coverage',
  #   'eeObject': only_coverage([3,5,6],degradation_secondary_vegetation_coverage, degradation_secondary_vegetation_coverage),
  #   'visParams': visParams["lulc"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Degradation col 9 Forests - Secondary Vegetation Age',
  #   'eeObject': only_coverage([3,5,6],degradation_secondary_vegetation_age, degradation_secondary_vegetation_coverage),
  #   'visParams': visParams["secondary_vegetation_age"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Degradation col 9 Forests - Fire Frequency',
  #   'eeObject': only_coverage([3,5,6],degradation_fire_frequency,landcover_base),
  #   'visParams': visParams["frequency"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Degradation col 9 Forests - Fire Age',
  #   'eeObject': only_coverage([3,5,6],degradation_fire_age,landcover_base.slice(1)),
  #   'visParams': visParams["fire_age"]
  # },
  # {
  #   'type': 'image',
  #   'name': 'Degradation col 9 Forests - Accumulated Burned Coverage',
  #   'eeObject': only_coverage([3,5,6],degradation_accumulated_burned_coverage,degradation_accumulated_burned_coverage),
  #   'visParams': visParams["lulc"]
  # }

]

print(datasets)

"""# Step 4 - Setup of Vector Maps

In this step, you will configure the vector maps that will be used in the analysis. These vector maps will be employed in the loop to process the raster maps according to specific geographical boundaries. This step ensures that the analysis is conducted within the defined regions of interest.

"""

# step 4: Set up the vector maps that will be used to define geographical boundaries in the analysis.
# These vectors will be utilized in the processing loop to clip or analyze raster data within specific regions.
ufs = ee.FeatureCollection('projects/mapbiomas-workspace/AUXILIAR/estados-2017')

territories = {
    'Paraguay': {
        'features': ee.FeatureCollection('FAO/GAUL/2015/level0').filter(ee.Filter.eq('ADM0_NAME', 'Paraguay')),
    },

    # 'Brasil': {
    #     'features': ee.FeatureCollection('projects/mapbiomas-workspace/AUXILIAR/biomas_IBGE_250mil'),
    # },
  #   'Amazônia': {
  #       'features': ee.FeatureCollection('projects/mapbiomas-workspace/AUXILIAR/biomas_IBGE_250mil').filter(ee.Filter.eq('Bioma','Amazônia')),
  #   },
  #   'Caatinga': {
  #       'features': ee.FeatureCollection('projects/mapbiomas-workspace/AUXILIAR/biomas_IBGE_250mil').filter(ee.Filter.eq('Bioma','Caatinga')),
  #   },
  #   'Cerrado': {
  #       'features': ee.FeatureCollection('projects/mapbiomas-workspace/AUXILIAR/biomas_IBGE_250mil').filter(ee.Filter.eq('Bioma','Cerrado')),
  #   },
  #   'Mata Atlântica': {
  #       'features': ee.FeatureCollection("users/wallacesilva/mata_atlantica_"), ## mata atlantica sem as ilhas
  #   },
  #   'Pampa': {
  #       'features': ee.FeatureCollection('projects/mapbiomas-workspace/AUXILIAR/biomas_IBGE_250mil').filter(ee.Filter.eq('Bioma','Pampa')),
  #   },
  #  'Pantanal': {
  #       'features': ee.FeatureCollection('projects/mapbiomas-workspace/AUXILIAR/biomas_IBGE_250mil').filter(ee.Filter.eq('Bioma','Pantanal')),
  #   },
  #   'BAP': {
  #     'features': ee.FeatureCollection('projects/ee-arcplan/assets/bap_pantanal_planalto'),
  #   },
  #   'BAP_planalto': {
  #     'features': ee.FeatureCollection('projects/ee-arcplan/assets/bap_pantanal_planalto').filter(ee.Filter.equals('name_pt_br','Planalto')),
  #   },
  #  'Matopiba': {
  #       'features': ee.FeatureCollection('projects/mapbiomas-workspace/AUXILIAR/ESTATISTICAS/COLECAO8/VERSAO-1/matopiba'),
  #   },
  #   'Matopiba_cerrado': {
  #       'features': ee.FeatureCollection([ee.FeatureCollection('projects/mapbiomas-workspace/AUXILIAR/ESTATISTICAS/COLECAO8/VERSAO-1/matopiba').geometry().intersection(ee.FeatureCollection('projects/mapbiomas-workspace/AUXILIAR/biomas_IBGE_250mil').filter(ee.Filter.eq('Bioma', 'Cerrado')).geometry())]),
  #   },
#   "CENTRO-OESTE":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","CENTRO-OESTE"))},
#   "NORDESTE":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","NORDESTE"))},
#   "NORTE":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","NORTE"))},
#   "SUDESTE":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","SUDESTE"))},
#   "SUL":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","SUL"))},
#   "CENTRO-OESTE":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","CENTRO-OESTE"))},
#   "NORDESTE":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","NORDESTE"))},
#   "NORTE":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","NORTE"))},
#   "SUDESTE":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","SUDESTE"))},
#   "SUL":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","SUL"))},
#   "CENTRO-OESTE":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","CENTRO-OESTE"))},
#   "NORDESTE":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","NORDESTE"))},
#   "NORTE":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","NORTE"))},
#   "SUDESTE":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","SUDESTE"))},
#   "SUL":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","SUL"))},
#   "CENTRO-OESTE":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","CENTRO-OESTE"))},
#   "NORDESTE":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","NORDESTE"))},
#   "NORTE":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","NORTE"))},
#   "SUDESTE":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","SUDESTE"))},
#   "SUL":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","SUL"))},
#   "CENTRO-OESTE":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","CENTRO-OESTE"))},
#   "NORDESTE":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","NORDESTE"))},
#   "NORTE":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","NORTE"))},
#   "SUDESTE":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","SUDESTE"))},
#   "SUL":{"features":ufs.filter(ee.Filter.equals("NM_REGIAO","SUL"))},
#   "ACRE":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","ACRE"))},
#   "ALAGOAS":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","ALAGOAS"))},
#   "AMAPÁ":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","AMAPÁ"))},
#   "AMAZONAS":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","AMAZONAS"))},
  # "BAHIA":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","BAHIA"))},
#   "CEARÁ":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","CEARÁ"))},
#   "DISTRITO FEDERAL":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","DISTRITO FEDERAL"))},
#   "ESPÍRITO SANTO":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","ESPÍRITO SANTO"))},
#   "GOIÁS":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","GOIÁS"))},
#   "MARANHÃO":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","MARANHÃO"))},
#   "MATO GROSSO":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","MATO GROSSO"))},
#   "MATO GROSSO DO SUL":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","MATO GROSSO DO SUL"))},
#   "MINAS GERAIS":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","MINAS GERAIS"))},
#   "PARANÁ":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","PARANÁ"))},
#   "PARAÍBA":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","PARAÍBA"))},
#   "PARÁ":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","PARÁ"))},
#   "PERNAMBUCO":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","PERNAMBUCO"))},
#   "PIAUÍ":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","PIAUÍ"))},
#   "RIO DE JANEIRO":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","RIO DE JANEIRO"))},
#   "RIO GRANDE DO NORTE":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","RIO GRANDE DO NORTE"))},
#   "RIO GRANDE DO SUL":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","RIO GRANDE DO SUL"))},
#   "RONDÔNIA":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","RONDÔNIA"))},
#   "RORAIMA":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","RORAIMA"))},
#   "SANTA CATARINA":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","SANTA CATARINA"))},
#   "SERGIPE":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","SERGIPE"))},
#   "SÃO PAULO":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","SÃO PAULO"))},
#   "TOCANTINS":{"features":ufs.filter(ee.Filter.equals("NM_ESTADO","TOCANTINS"))},
}

"""# Step 5 - Main Functions of the Routine

In this step, the main functions that drive the processing routine are defined. These functions will handle tasks such as downloading images, applying visualizations, and generating outputs. The functions developed in this step are crucial for the automation and customization of the workflow, and they may be of interest to other developers who want to adapt or extend the code for different projects.

"""

# step 5: Define the main functions that will be used in the processing routine.
# These functions automate tasks like downloading images, applying visualizations, and saving outputs.

# Função para gerar links de download de imagens do Earth Engine
def generate_image_links(dataset, region, vertical_dimension=1560, aspect_ratio=1.5):
    links = []
    visParam = dataset['visParams']  # Acessar diretamente visParams, sem loop
    # print('dataset',dataset)
    # print("dataset['eeObject'].bandNames()",dataset['eeObject'])
    bandnames = dataset['eeObject'].bandNames().getInfo()


    for bandname in bandnames:
        visParam_copy = visParam.copy()  # Copiar visParam para não modificar o original
        visParam_copy['bands'] = [bandname]
        try:
            image = (dataset['eeObject']
                     .select(bandname)
                     .unmask()
                     .visualize(**visParam_copy)
                     .updateMask(ee.Image().paint(region).eq(0))
                     .blend(ee.Image().paint(region,'vazio',1))
                     )

            dimensions = f"{vertical_dimension}"
            url = image.getThumbURL({'dimensions': dimensions, 'region': region.geometry().bounds()})
            links.append({'name': f"{dataset['name']}-{dimensions}-{bandname}", 'link': url})
        except ee.EEException as e:
            print(f"Erro ao visualizar a imagem para a banda {bandname}: {e}")

    return links

# Function to add text to an image using OpenCV
def add_text_to_image(image_path, text, position='top_left', font_size=48, background='white'):
    # Open the image with PIL and convert to a numpy array
    image = PILImage.open(image_path)
    image_np = np.array(image)

    # Convert the image to BGRA (OpenCV uses BGR, add alpha channel if necessary)
    if len(image_np.shape) == 2:  # Grayscale
        image_np = cv2.cvtColor(image_np, cv2.COLOR_GRAY2BGRA)
    elif image_np.shape[2] == 3:  # RGB
        image_np = cv2.cvtColor(image_np, cv2.COLOR_RGB2BGRA)
    elif image_np.shape[2] == 4:  # RGBA
        image_np = cv2.cvtColor(image_np, cv2.COLOR_RGBA2BGRA)

    # Define the text position
    text_positions = {
        'top_left': (30, 50),
        'top_right': (image_np.shape[1] - 180, 60),  # Move left by 180 pixels for visibility
        'bottom_left': (10, image_np.shape[0] - 10),
        'bottom_right': (image_np.shape[1] - 180, image_np.shape[0] - 10),  # Move left by 180 pixels
    }
    text_position = text_positions.get(position, (10, 40))  # Default: top left

    # Add text to the image using OpenCV
    font = cv2.FONT_HERSHEY_SIMPLEX
    font_scale = font_size / 24  # Adjust font scale based on desired size
    font_thickness = 2
    text_color = (255, 255, 255, 255)  # White with alpha
    outline_color = (0, 0, 0, 255)  # Black with alpha

    # Measure the text size
    text_size = cv2.getTextSize(text, font, font_scale, font_thickness)[0]

    # Define the background rectangle
    rect_color = (255, 255, 255, 255) if background == 'white' else (255, 255, 255, 0)  # Transparent if not white
    rect_top_left = (text_position[0] - 5, text_position[1] - text_size[1] - 5)
    rect_bottom_right = (text_position[0] + text_size[0] + 5, text_position[1] + 5)

    # Add background rectangle (preserve transparency if needed)
    cv2.rectangle(image_np, rect_top_left, rect_bottom_right, rect_color, thickness=cv2.FILLED)

    # Add text outline
    cv2.putText(image_np, text, text_position, font, font_scale, outline_color, font_thickness + 1, cv2.LINE_AA)
    # Add the text
    cv2.putText(image_np, text, text_position, font, font_scale, text_color, font_thickness, cv2.LINE_AA)

    # Convert the image back to PIL while maintaining the alpha channel
    image_with_text = PILImage.fromarray(cv2.cvtColor(image_np, cv2.COLOR_BGRA2RGBA))
    image_with_text.save(image_path)

def download_and_save_images(dataset, territory_name, region, territory_path, vertical_dimension=2500):
    # Supondo que a função 'generate_image_links' já esteja ajustada para lidar com a proporção automaticamente
    list_links = generate_image_links(dataset, region, vertical_dimension)
    images = []

    for obj in list_links:
        image_url = obj['link']
        r = requests.get(image_url, stream=True)
        output_name = os.path.join(territory_path, f"{obj['name']}.png")

        with open(output_name, "wb") as png:
            for chunk in r.iter_content(chunk_size=1024):  # Pode ajustar o tamanho do chunk
                if chunk:  # Filtra os keep-alive chunks
                    png.write(chunk)
        print(f"Downloaded {obj['name']} to {territory_path}")

        # Adicionar o ano à imagem
        year = obj['name'].split('-')[-1]
        # add_text_to_image(output_name, year[-2:] + '-' + year[-6:-2],'top_left') # adaptação do titulo com a data de cada frame para o Monitor do Fogo
        add_text_to_image(output_name, year[-4:],'top_left')

        # Redimensionar a imagem mantendo a proporção de aspecto original
        image = PILImage.open(output_name)
        original_size = image.size
        aspect_ratio = original_size[0] / original_size[1]
        new_size = (int(vertical_dimension * aspect_ratio), vertical_dimension)
        image = image.resize(new_size, PILImage.Resampling.LANCZOS)  # Ajusta a resolução conforme necessário
        image.save(output_name)

        # Adicionar a imagem à lista para o GIF
        images.append(imageio.imread(output_name))

    return images

# Function to create and display a GIF
def create_and_display_gif(images, dataset_name, territory_path, bolean_display):
    if images:
        # Resize images to a common size before creating GIF
        common_shape = min([img.shape for img in images])  # Find smallest dimensions
        resized_images = [cv2.resize(img, (common_shape[1], common_shape[0])) for img in images]

        # Ensure the directory exists before saving
        if not os.path.exists(territory_path):
            os.makedirs(territory_path)
            print(f"Created directory: {territory_path}")

        # gif_filename = os.path.join(territory_path, f"{dataset_name}-GIF.gif")
        gif_filename = os.path.join(territory_path, f"{dataset_name}-GIF.gif")

        try:
            imageio.mimsave(gif_filename, resized_images, format='GIF', duration=300, loop=1000)
            print(f"GIF saved as {gif_filename}")
        except Exception as e:
            print(f"Error saving GIF: {e}")

        if bolean_display != False:

          # Optimize image resolution for the collage
          optimized_images = [cv2.resize(img, (common_shape[1] // 2, common_shape[0] // 2)) for img in resized_images]

          # Display thumbnails in a grid
          num_images = len(optimized_images)
          grid_size = int(np.ceil(np.sqrt(num_images)))

          fig, ax = plt.subplots(grid_size, grid_size, figsize=(10, 10))
          plt.subplots_adjust(wspace=0, hspace=0)  # Remove space between subplots

          for i, img in enumerate(optimized_images):
              row = i // grid_size
              col = i % grid_size
              ax[row, col].imshow(img)
              ax[row, col].axis('off')

          # Turn off unused axes
          for i in range(num_images, grid_size * grid_size):
              fig.delaxes(ax.flatten()[i])

          quadro_filename = os.path.join(territory_path, f"{dataset_name}-image-collage.png")
          try:
              plt.savefig(quadro_filename, bbox_inches='tight', pad_inches=0)
              plt.show()
              print(f"Image collage saved as {quadro_filename}")
          except Exception as e:
              print(f"Error saving image collage: {e}")

    else:
        print(f"No images available to create GIF for {dataset_name}")

"""# Step 6 - Loop to Generate and Save Frames on Google Drive

In this step, a loop is implemented to process the datasets and territories defined in previous steps. The loop will generate frames based on the configured input data and save them to the specified Google Drive directory. This step automates the creation of images for each year and region, ensuring that the outputs are organized and stored efficiently.

"""

# step 6: Implement a loop to generate and save frames to Google Drive.
# This loop processes each dataset and territory, creating images for each year and saving them in the specified directory.

# Inicializar contadores e tempos
total_datasets = len(datasets)
dataset_counter = 0

start_time = time.time()

for dataset in datasets:
    dataset_start_time = time.time()
    dataset_counter += 1

    # Path to the dataset directory
    dataset_path = os.path.join(main_path, dataset['name'])

    if not os.path.exists(dataset_path):
        os.makedirs(dataset_path)
        print(f"Created dataset directory: {dataset_path}")
    else:
        print(f"Dataset directory already exists: {dataset_path}")

    # Start processing visualization parameters
    visparam_start_time = time.time()

    # Process each territory within the dataset
    for territory_name, territory_info in territories.items():
        territory_start_time = time.time()

        # Path to the territory directory, now directly inside dataset_path
        territory_path = os.path.join(dataset_path, territory_name)

        if not os.path.exists(territory_path):
            os.makedirs(territory_path)
            print(f"Created territory directory: {territory_path}")
        else:
            print(f"Territory directory already exists: {territory_path}")

        region = territory_info['features']

        # Download and save images
        images = download_and_save_images(dataset, territory_name, region, territory_path)

        territory_end_time = time.time()
        print(f"Territory {territory_name} completed in {territory_end_time - territory_start_time:.2f} seconds")

    visparam_end_time = time.time()
    print(f"VisParam processing completed in {visparam_end_time - visparam_start_time:.2f} seconds")

    dataset_end_time = time.time()
    print(f"Dataset {dataset_counter}/{total_datasets} completed in {dataset_end_time - dataset_start_time:.2f} seconds")

# Fim do processo de download e salvamento de imagens
end_time = time.time()
print(f"All datasets processed in {end_time - start_time:.2f} seconds")

# step 7: Implement a loop to generate GIFs from the saved images and save them to Google Drive.
# This loop processes the images created in the previous step, generating GIFs for each territory and year.

for dataset in datasets:
    dataset_path = os.path.join(main_path, dataset['name'])

    for territory_name in territories.keys():
        # Diretório do território diretamente dentro do dataset_path
        territory_path = os.path.join(dataset_path, territory_name)
        images = []

        # Verificação de caminho
        print(f"Verificando o caminho: {territory_path}")

        # Carregar imagens previamente baixadas
        if os.path.exists(territory_path):  # Verificar se o caminho do território existe
            for file in os.listdir(territory_path):
                if file.endswith(".png"):
                    image_path = os.path.join(territory_path, file)
                    print(f"Lendo imagem de: {image_path}")
                    images.append(imageio.imread(image_path))
        else:
            print(f"Directory does not exist: {territory_path}")
            continue  # Pular para o próximo território se o diretório não existir

        # Criar e exibir GIF e thumbnails
        create_and_display_gif(images, dataset['name'], territory_path, True)

print("All GIFs generated successfully.")

