name: "Biomes"
description: "Brazilian biomes"
type: biomes
territories:
  biomas_todos:
    name: "Biomas"
    name_en: "All Biomes"
    source: "projects/ee-ipam/assets/IBGE/limite_biomas_IBGE_2026"
    bbox: [-74.0, -34.0, -34.0, 5.0]
  bioma_amazonia:
    name: "Amazônia"
    source: "projects/ee-ipam/assets/IBGE/limite_biomas_IBGE_2026"
    filter: "Bioma == 'Amazônia'"
    bbox: [-74.0, -18.0, -44.0, 5.0]
  bioma_caatinga:
    name: "Caatinga"
    source: "projects/ee-ipam/assets/IBGE/limite_biomas_IBGE_2026"
    filter: "Bioma == 'Caatinga'"
    bbox: [-48.0, -18.0, -36.0, -3.0]
  bioma_cerrado:
    name: "Cerrado"
    source: "projects/ee-ipam/assets/IBGE/limite_biomas_IBGE_2026"
    filter: "Bioma == 'Cerrado'"
    bbox: [-56.0, -24.0, -40.0, -2.0]
  bioma_mata_atlantica:
    name: "Mata Atlântica"
    source: "users/wallacesilva/mata_atlantica_"
    bbox: [-56.0, -30.0, -32.0, -2.0]
  bioma_pampa:
    name: "Pampa"
    source: "projects/ee-ipam/assets/IBGE/limite_biomas_IBGE_2026"
    filter: "Bioma == 'Pampa'"
    bbox: [-58.0, -34.0, -50.0, -28.0]
  bioma_pantanal:
    name: "Pantanal"
    source: "projects/ee-ipam/assets/IBGE/limite_biomas_IBGE_2026"
    filter: "Bioma == 'Pantanal'"
    bbox: [-58.0, -22.0, -55.0, -17.0]
