territories:
  custom_regions:
    matopiba_cerrado:
      name: "MATOPIBA no Cerrado"
      name_en: "MATOPIBA in Cerrado"
      source: "users/dh-conciani/vectors/matopiba_lapig_cerrado"
      bbox: [-50.0, -16.0, -41.0, -2.0]
    matopiba:
      name: "MATOPIBA"
      name_en: "MATOPIBA"
      source: "projects/mapbiomas-workspace/AUXILIAR/ESTATISTICAS/COLECAO8/VERSAO-1/matopiba"
      bbox: [-50.0, -16.0, -41.0, -2.0]
    centro_oeste:
      name: "Centro-Oeste"
      source: "projects/mapbiomas-workspace/AUXILIAR/estados-2017"
      filter: "NM_REGIAO == 'CENTRO-OESTE'"
    nordeste:
      name: "Nordeste"
      source: "projects/mapbiomas-workspace/AUXILIAR/estados-2017"
      filter: "NM_REGIAO == 'NORDESTE'"
    norte:
      name: "Norte"
      source: "projects/mapbiomas-workspace/AUXILIAR/estados-2017"
      filter: "NM_REGIAO == 'NORTE'"
    sudeste:
      name: "Sudeste"
      source: "projects/mapbiomas-workspace/AUXILIAR/estados-2017"
      filter: "NM_REGIAO == 'SUDESTE'"
    sul:
      name: "Sul"
      source: "projects/mapbiomas-workspace/AUXILIAR/estados-2017"
      filter: "NM_REGIAO == 'SUL'"
    bap:
      name: "BAP"
      name_en: "BAP"
      source: "projects/ee-arcplan/assets/bap_pantanal_planalto"
      bbox: [-58.0, -22.0, -55.0, -17.0]
    bap_planalto:
      name: "BAP Planalto"
      name_en: "BAP Planalto"
      source: "projects/ee-arcplan/assets/bap_pantanal_planalto"
      filter: "name_pt_br == 'Planalto'"
      bbox: [-58.0, -22.0, -55.0, -17.0]
