territories:
  countries:
    paraguay:
      name: "Paraguai"
      name_en: "Paraguay"
      source: "FAO/GAUL/2015/level0"
      filter: "ADM0_NAME == 'Paraguay'"
      bbox: [-62.0, -27.5, -54.0, -19.0]
    brasil:
      name: "Brasil"
      name_en: "Brazil"
      source: "FAO/GAUL/2015/level0"
      filter: "ADM0_NAME == 'Brazil'"
      bbox: [-74.0, -34.0, -34.0, 5.0]
    brasil_biomes:
      name: "Brasil - Biomas"
      name_en: "Brazil - Biomes"
      source: "FAO/GAUL/2015/level0"
      filter: "ADM0_NAME == 'Brazil'"
      bbox: [-74.0, -34.0, -34.0, 5.0]
      overlay_source: "projects/mapbiomas-workspace/AUXILIAR/biomas_IBGE_250mil"
