visualizations:
  random:
    name: "Fragmentos de Vegetação"
    min: 0
    max: 1
    palette: []
    random_viz: true
    cmap_type: "binary"
    label: "Cada fragmento possui uma cor distinta"

  fire:
    name: "Fogo - Binário"
    min: 0
    max: 1
    palette:
      - "fdfdfd"
      - "800000"
    label: "Pixel queimado"
    cmap_type: "binary"

  monthly:
    name: "Fogo - Mês"
    min: 0
    max: 12
    palette:
      - "fdfdfd"
      - "55E3E6"
      - "27d3c3"
      - "00c29b"
      - "19b06f"
      - "08cf26"
      - "53e300"
      - "dbc900"
      - "ff8800"
      - "ff3c00"
      - "df2a02"
      - "c01702"
      - "a10000"
    label: "Mês de queimada (1=Jan, 12=Dez)"
    cmap_type: "sequential"

  frequency:
    name: "Fogo - Frequência"
    min: 0
    max: 11
    palette:
      - "fdfdfd"
      - "faf3cd"
      - "fce68d"
      - "f9de44"
      - "f6d51d"
      - "e9bc1c"
      - "cc8715"
      - "b76011"
      - "9f360b"
      - "810004"
      - "4b0709"
      - "080202"
    label: "Frequência de queimadas (1985-2023)"
    cmap_type: "sequential"

  frequency_col101:
    name: "Fogo - Frequência (Degradação)"
    min: 0
    max: 40
    palette:
      - "808080"
      - "faf3cd"
      - "f8ea94"
      - "f6e154"
      - "f4d81d"
      - "e9bc1c"
      - "d99d18"
      - "cc8715"
      - "bf7012"
      - "b2560f"
      - "a43e0c"
      - "962809"
      - "881806"
      - "7a0b04"
      - "6c0705"
      - "5e0807"
      - "500809"
      - "42070a"
      - "34060b"
      - "28050b"
      - "1c0408"
      - "140306"
      - "0c0204"
      - "080203"
      - "040101"
    label: "Frequência de fogo (1985-2024)"
    cmap_type: "sequential"

  frequency_paraguay:
    name: "Fogo - Frequência (Paraguai)"
    min: 0
    max: 26
    palette:
      - "ffffff"
      - "faf3cd"
      - "fced97"
      - "fae154"
      - "f8d823"
      - "eec41d"
      - "e1ae1a"
      - "d49616"
      - "ca8315"
      - "bd6c12"
      - "b25810"
      - "a6420d"
      - "9a2b0a"
      - "8f1807"
      - "800004"
      - "6d0306"
      - "5d0407"
      - "4b0709"
      - "410708"
      - "370608"
      - "2e0506"
      - "240505"
      - "1b0404"
      - "130303"
      - "0b0203"
      - "040101"
    label: "Frequência de queimadas (Paraguai)"
    cmap_type: "sequential"

  lulc:
    name: "Uso e Cobertura"
    min: 0
    max: 62
    palette:
      - "ffffff"
      - "32a65e"
      - "32a65e"
      - "1f8d49"
      - "7dc975"
      - "04381d"
      - "026975"
      - "000000"
      - "000000"
      - "7a6c00"
      - "ad975a"
      - "519799"
      - "d6bc74"
      - "d89f5c"
      - "FFFFB2"
      - "edde8e"
      - "000000"
      - "000000"
      - "f5b3c8"
      - "C27BA0"
      - "db7093"
      - "ffefc3"
      - "db4d4f"
      - "ffa07a"
      - "d4271e"
      - "db4d4f"
      - "0000FF"
      - "000000"
      - "000000"
      - "ffaa5f"
      - "9c0027"
      - "091077"
      - "fc8114"
      - "2532e4"
      - "93dfe6"
      - "9065d0"
      - "d082de"
      - "000000"
      - "000000"
      - "f5b3c8"
      - "c71585"
      - "f54ca9"
      - "cca0d4"
      - "dbd26b"
      - "807a40"
      - "e04cfa"
      - "d68fe2"
      - "9932cc"
      - "e6ccff"
      - "02d659"
      - "ad5100"
      - "000000"
      - "000000"
      - "000000"
      - "000000"
      - "000000"
      - "000000"
      - "CC66FF"
      - "FF6666"
      - "006400"
      - "8d9e8b"
      - "f5d5d5"
      - "ff69b4"
    label: "Classe de uso"
    cmap_type: "categorical"

  scar_size_range:
    name: "Tamanho da Cicatriz"
    min: 0
    max: 10
    palette:
      - "ffffff"
      - "d0ae35"
      - "d08d29"
      - "cc6c28"
      - "c2482e"
      - "b31e35"
      - "931f28"
      - "741e1d"
      - "571a14"
      - "3c150b"
      - "240d00"
    label: "Classe de tamanho"
    cmap_type: "sequential"

  year_last_fire:
    name: "Ano do Último Fogo"
    min: 1985
    max: 2022
    palette:
      - "ffffff"
      - "000079"
      - "00147d"
      - "00227f"
      - "002d81"
      - "003781"
      - "004080"
      - "004c7b"
      - "00557f"
      - "005e86"
      - "00688c"
      - "007292"
      - "007d96"
      - "008998"
      - "0a9294"
      - "26A09E"
      - "41ACA6"
      - "5DB9AD"
      - "78C5B5"
      - "94D2BD"
      - "9FBD98"
      - "AAA772"
      - "B4924D"
      - "BF7C27"
      - "CA6702"
      - "C45905"
      - "BF4B08"
      - "B93C0C"
      - "B42E0F"
      - "AE2012"
      - "AA2016"
      - "A6211A"
      - "A3211E"
      - "9F2222"
      - "9B2226"
      - "961B1E"
      - "901417"
      - "8B0E0F"
      - "850708"
      - "800000"
      - "800000"
    label: "Ano"
    cmap_type: "sequential"

  year_next_fire:
    name: "Ano do Próximo Fogo"
    min: 1986
    max: 2023
    palette:
      - "ffffff"
      - "000079"
      - "00147d"
      - "00227f"
      - "002d81"
      - "003781"
      - "004080"
      - "004c7b"
      - "00557f"
      - "005e86"
      - "00688c"
      - "007292"
      - "007d96"
      - "008998"
      - "0a9294"
      - "26A09E"
      - "41ACA6"
      - "5DB9AD"
      - "78C5B5"
      - "94D2BD"
      - "9FBD98"
      - "AAA772"
      - "B4924D"
      - "BF7C27"
      - "CA6702"
      - "C45905"
      - "BF4B08"
      - "B93C0C"
      - "B42E0F"
      - "AE2012"
      - "AA2016"
      - "A6211A"
      - "A3211E"
      - "9F2222"
      - "9B2226"
      - "961B1E"
      - "901417"
      - "8B0E0F"
      - "850708"
      - "800000"
      - "800000"
    label: "Ano"
    cmap_type: "sequential"

  fire_age:
    name: "Idade do Fogo"
    min: 0
    max: 39
    palette:
      - "808080"
      - "800000"
      - "800000"
      - "850708"
      - "8B0E0F"
      - "901417"
      - "961B1E"
      - "9B2226"
      - "9F2222"
      - "A3211E"
      - "A6211A"
      - "AA2016"
      - "AE2012"
      - "B42E0F"
      - "B93C0C"
      - "BF4B08"
      - "C45905"
      - "CA6702"
      - "BF7C27"
      - "B4924D"
      - "AAA772"
      - "9FBD98"
      - "94D2BD"
      - "78C5B5"
      - "5DB9AD"
      - "41ACA6"
      - "26A09E"
      - "0A9294"
      - "008998"
      - "007D96"
      - "007292"
      - "00688C"
      - "005E86"
      - "00557F"
      - "004C7B"
      - "004080"
      - "003781"
      - "002D81"
      - "00227F"
      - "00147D"
      - "000079"
    label: "Anos desde o fogo"
    cmap_type: "sequential"

  def_seco:
    name: "Desmatamento e Vegetação Secundária"
    min: 0
    max: 7
    palette:
      - "ffffff"
      - "fff6bf"
      - "127622"
      - "56d117"
      - "ea1c1c"
      - "6fc4b7"
      - "ffb66c"
      - "8c8c8c"
    label: "Classe"
    cmap_type: "categorical"

  soc:
    name: "Carbono Orgânico do Solo"
    min: -1
    max: 80
    palette:
      - "ffffff"
      - "ffffe5"
      - "fff7bc"
      - "fee391"
      - "fec44f"
      - "fe9929"
      - "ec7014"
      - "cc4c02"
      - "993404"
      - "662506"
    label: "t/ha"
    unit: "t/ha"
    cmap_type: "sequential"

  edge_area_col101:
    name: "Distância da Borda"
    min: 0
    max: 8
    palette:
      - "808080"
      - "E31A1C"
      - "FEB24C"
      - "B2DF8A"
      - "33A02C"
      - "7289AB"
      - "3F48CC"
      - "A059A0"
      - "E066FF"
    label: "Distância da borda (m)"
    cmap_type: "categorical"
    discrete_labels:
      - "Sem vegetação"
      - "<= 30 m"
      - "<= 60 m"
      - "<= 90 m"
      - "<= 120 m"
      - "<= 150 m"
      - "<= 300 m"
      - "<= 600 m"
      - "<= 1000 m"

  edge_age_col101:
    name: "Idade da Borda"
    min: 0
    max: 40
    palette:
      - "808080"
      - "33A02C"
      - "49AB3C"
      - "60B64D"
      - "77C15E"
      - "8ECD6F"
      - "A4D880"
      - "B4E083"
      - "BBE373"
      - "C1E664"
      - "C8E954"
      - "CEEC44"
      - "D5EF35"
      - "DCEC2B"
      - "E3E721"
      - "EBE318"
      - "F2DE0F"
      - "F9DA06"
      - "FFD300"
      - "FFC500"
      - "FFB800"
      - "FFAA00"
      - "FF9D00"
      - "FF8F00"
      - "FB7D03"
      - "F66808"
      - "F1540D"
      - "EC3F12"
      - "E72B17"
      - "E11B1F"
      - "D52637"
      - "C9324E"
      - "BD3D66"
      - "B1487E"
      - "A55495"
      - "9A51A7"
      - "9043B5"
      - "8735C3"
      - "7D28D1"
      - "731ADF"
      - "6A0DED"
    label: "Idade da borda (anos)"
    cmap_type: "sequential"
    unit: "anos"

  edge_area:
    name: "Proximidade de Borda"
    min: 0
    max: 9
    palette:
      - "55604B"
      - "FF0001"
      - "32CD32"
      - "19B06F"
      - "6FA8DC"
      - "0B5394"
      - "A64D79"
      - "F54CA9"
      - "55604B"
    label: "Distância de borda (m)"
    cmap_type: "sequential"

  distances:
    name: "Distância de Isolamento"
    min: 0
    max: 12
    palette:
      - "55604B"
      - "000080"
      - "0000ff"
      - "8080ff"
      - "008000"
      - "00ff00"
      - "80ff80"
      - "800000"
      - "ff0000"
      - "FF8080"
      - "55604B"
      - "55604B"
      - "55604B"
    label: "Classe de distância"
    cmap_type: "sequential"

  patch_size:
    name: "Tamanho de Fragmento"
    min: 0
    max: 7
    palette:
      - "A9A9A9"
      - "E50C08"
      - "FFAA5F"
      - "32CD32"
      - "19B06F"
      - "6FA8DC"
      - "0B5394"
      - "A9A9A9"
    label: "Tamanho do fragmento (ha)"
    cmap_type: "categorical"
    discrete_labels:
      - "Não observado"
      - ""

  burned_at_least_once:
    name: "Queimado ao Menos uma Vez"
    min: 0
    max: 4
    palette:
      - "808080"
      - "FF8C00"
      - "DC143C"
      - "FFD700"
      - "8B4513"
    label: "Frequência de fogo"
    cmap_type: "categorical"
    discrete_labels:
      - "Não observado"
      - "Queimado ao menos uma vez"
      - "Queimado pela primeira vez"
      - "Queimará no futuro"
      - "Natural queimado e convertido"

  secondary_vegetation_coverage:
    name: "Cobertura da Vegetação Secundária"
    min: 0
    max: 62
    palette:
      - "808080"
      - "32a65e"
      - "32a65e"
      - "1f8d49"
      - "7dc975"
      - "04381d"
      - "026975"
      - "000000"
      - "000000"
      - "7a6c00"
      - "ad975a"
      - "519799"
      - "d6bc74"
      - "d89f5c"
      - "FFFFB2"
      - "edde8e"
      - "000000"
      - "000000"
      - "f5b3c8"
      - "C27BA0"
      - "db7093"
      - "ffefc3"
      - "db4d4f"
      - "ffa07a"
      - "d4271e"
      - "db4d4f"
      - "0000FF"
      - "000000"
      - "000000"
      - "ffaa5f"
      - "9c0027"
      - "091077"
      - "fc8114"
      - "2532e4"
      - "93dfe6"
      - "9065d0"
      - "d082de"
      - "000000"
      - "000000"
      - "f5b3c8"
      - "c71585"
      - "f54ca9"
      - "cca0d4"
      - "dbd26b"
      - "807a40"
      - "e04cfa"
      - "d68fe2"
      - "9932cc"
      - "e6ccff"
      - "02d659"
      - "ad5100"
      - "000000"
      - "000000"
      - "000000"
      - "000000"
      - "000000"
      - "000000"
      - "CC66FF"
      - "FF6666"
      - "006400"
      - "8d9e8b"
      - "f5d5d5"
      - "ff69b4"
    label: "Classe de cobertura"
    cmap_type: "categorical"
    discrete_labels:
      - "Não observado"
      - ""
      - ""
      - "Formação Florestal"
      - "Formação Savânica"
      - "Mangue"
      - "Floresta Alagável"
      - ""
      - ""
      - ""
      - ""
      - "Campo Alagado e Área Pantanosa"
      - "Formação Campestre"
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - "Apicum"
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - "Restinga Arbórea"
      - "Restinga Herbácea"
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""

  morphology:
    name: "Morfologia do Fragmento"
    min: 0
    max: 6
    palette:
      - "808080"
      - "34662B"
      - "9BCFB3"
      - "46A9B1"
      - "FFCC4A"
      - "F6B0CB"
      - "A9DBEB"
    label: "Classe morfológica"
    cmap_type: "categorical"
    discrete_labels:
      - "Sem vegetação"
      - "Núcleo"
      - "Borda"
      - "Perfuração"
      - "Mancha"
      - "Laço"
      - "Ponte"

  secondary_vegetation_age:
    name: "Idade da Vegetação Secundária"
    min: 0
    max: 39
    palette:
      - "808080"
      - "F3F6C2"
      - "F1F6A1"
      - "EFF680"
      - "EEF660"
      - "EDF63F"
      - "EAF622"
      - "D9F622"
      - "C8F622"
      - "B6F622"
      - "A4F622"
      - "8EF622"
      - "79F622"
      - "71F622"
      - "67F623"
      - "5DF625"
      - "55F627"
      - "4DF629"
      - "41F62A"
      - "39F62C"
      - "31F62E"
      - "28F62F"
      - "22F430"
      - "22E72D"
      - "22DF2A"
      - "22D127"
      - "22C123"
      - "23B21F"
      - "23AA1C"
      - "23A21B"
      - "239A19"
      - "238F16"
      - "238513"
      - "237D11"
      - "237510"
      - "246D0D"
      - "24680C"
      - "24640B"
      - "24600A"
      - "255808"
    label: "Idade (anos)"
    cmap_type: "sequential"
