visualizations:

  edge_area_col101:
    name: "Distância da Borda"
    min: 0
    max: 8
    palette:
      - "505050"
      - "926228"
      - "a97729"
      - "c18c2b"
      - "b5a34d"
      - "97ba7e"
      - "81c79e"
      - "7cc099"
      - "77b995"
    label: "Distância da borda (m)"
    cmap_type: "categorical"
    discrete_labels:
      - "Não observado"
      - "≤ 30 m"
      - "≤ 60 m"
      - "≤ 90 m"
      - "≤ 120 m"
      - "≤ 150 m"
      - "≤ 300 m"
      - "≤ 600 m"
      - "≤ 1000 m"

  edge_age_col101:
    name: "Idade da Borda"
    min: 0
    max: 40
    palette:
      - "505050"
      - "6aca2a"
      - "6fc92b"
      - "75c92d"
      - "7ac82e"
      - "80c830"
      - "85c731"
      - "8ac633"
      - "90c634"
      - "95c536"
      - "9ac437"
      - "a0c439"
      - "a5c33a"
      - "abc33c"
      - "b0c23d"
      - "aebb3d"
      - "acb43d"
      - "aaad3d"
      - "a7a63d"
      - "a59f3d"
      - "a3983d"
      - "a1903e"
      - "9f893e"
      - "9d823e"
      - "9a7b3e"
      - "98743e"
      - "966d3e"
      - "94663e"
      - "8f623a"
      - "8b5e37"
      - "865933"
      - "82552f"
      - "7d512c"
      - "784d28"
      - "744824"
      - "6f4420"
      - "6a401d"
      - "663c19"
      - "613715"
      - "5d3312"
      - "582f0e"
    label: "Idade da borda (anos)"
    cmap_type: "sequential"
    unit: "anos"

  patch_size_continuous:
    name: "Tamanho do Fragmento (Contínuo)"
    min: 0
    max: 10000
    palette:
      - "505050"
      - "7a0103"
      - "9e1a1a"
      - "bc3523"
      - "d6542b"
      - "ed7634"
      - "f99b3e"
      - "ffc14a"
      - "ffea5d"
      - "e5f26d"
      - "c2e66b"
      - "99e6b3"
      - "57d18a"
      - "2eb872"
      - "239b89"
      - "1f808e"
      - "23668e"
      - "294d87"
      - "2a347a"
      - "1a1c5c"
      - "080a3d"
    label: "Tamanho do fragmento (ha)"
    cmap_type: "sequential"
    unit: "ha"

  patch_size_fragments:
    name: "Fragmentos (ate 10k ha)"
    min: 0
    max: 10
    palette:
      - "505050"
      - "7a0103"
      - "9e1a1a"
      - "bc3523"
      - "d6542b"
      - "ed7634"
      - "f99b3e"
      - "ffc14a"
      - "ffea5d"
      - "e5f26d"
      - "c2e66b"
    label: "Tamanho do fragmento"
    cmap_type: "categorical"
    discrete_labels:
      - "Não observado / > 10k ha"
      - "≤ 5 ha"
      - "≤ 10 ha"
      - "≤ 25 ha"
      - "≤ 50 ha"
      - "≤ 100 ha"
      - "≤ 250 ha"
      - "≤ 500 ha"
      - "≤ 1000 ha"
      - "≤ 5000 ha"
      - "≤ 10000 ha"

  patch_size_massifs:
    name: "Maciços (> 10k ha)"
    min: 0
    max: 10
    palette:
      - "505050"
      - "99e6b3"
      - "57d18a"
      - "2eb872"
      - "239b89"
      - "1f808e"
      - "23668e"
      - "294d87"
      - "2a347a"
      - "1a1c5c"
      - "080a3d"
    label: "Tamanho do maciço"
    cmap_type: "categorical"
    discrete_labels:
      - "Não observado / ≤ 10k ha"
      - "10k - 20k ha"
      - "20k - 50k ha"
      - "50k - 100k ha"
      - "100k - 250k ha"
      - "250k - 500k ha"
      - "500k - 1M ha"
      - "1M - 2.5M ha"
      - "2.5M - 5M ha"
      - "5M - 7.5M ha"
      - "> 7.5M ha"

  morphology:
    name: "Morfologia dos Fragmentos"
    min: 0
    max: 6
    palette:
      - "505050"
      - "1A9650"
      - "99D3B4"
      - "44AAB1"
      - "FFC941"
      - "FFADCE"
      - "A9DAE6"
    label: "Classe morfológica"
    cmap_type: "categorical"
    discrete_labels:
      - "Não observado"
      - "Interior"
      - "Borda"
      - "Corredor"
      - "Ramificação"
      - "Puleiro"
      - "Perfuração"

  secondary_vegetation_age:
    name: "Idade da Vegetação Secundária"
    min: 0
    max: 40
    palette:
      - "505050"
      - "F3F6C2"
      - "F1F6A1"
      - "EFF680"
      - "EEF660"
      - "EDF63F"
      - "EAF622"
      - "D9F622"
      - "C8F622"
      - "B6F622"
      - "A4F622"
      - "8EF622"
      - "79F622"
      - "71F622"
      - "67F623"
      - "5DF625"
      - "55F627"
      - "4DF629"
      - "41F62A"
      - "39F62C"
      - "31F62E"
      - "28F62F"
      - "22F430"
      - "22E72D"
      - "22DF2A"
      - "22D127"
      - "22C123"
      - "23B21F"
      - "23AA1C"
      - "23A21B"
      - "239A19"
      - "238F16"
      - "238513"
      - "237D11"
      - "237510"
      - "246D0D"
      - "24680C"
      - "24640B"
      - "24600A"
      - "255808"
      - "255407"
    label: "Idade (anos)"
    cmap_type: "sequential"
    unit: "anos"

  frequency_col101:
    name: "Fogo - Frequência (Degradação)"
    min: 0
    max: 40
    palette:
      - "505050"
      - "faf3cd"
      - "fdf1b0"
      - "fbe981"
      - "fae258"
      - "f9de44"
      - "f8d71f"
      - "f1ca1e"
      - "e9bc1c"
      - "e2af1a"
      - "daa118"
      - "d29316"
      - "cc8715"
      - "c57b14"
      - "bd6c12"
      - "b76011"
      - "b0540f"
      - "a8450d"
      - "9f360b"
      - "992a0a"
      - "921e08"
      - "8c1307"
      - "810004"
      - "770105"
      - "6a0306"
      - "600407"
      - "5a0508"
      - "4b0709"
      - "450709"
      - "3f0708"
      - "390608"
      - "330607"
      - "2d0506"
      - "270506"
      - "220505"
      - "1c0404"
      - "170404"
      - "120303"
      - "0d0203"
      - "080202"
      - "040101"
    label: "Frequência de fogo (1985-2024)"
    cmap_type: "sequential"

  fire_age:
    name: "Tempo desde o Último Fogo"
    min: 0
    max: 40
    palette:
      - "505050"
      - "750000"
      - "780000"
      - "810000"
      - "850708"
      - "8B0E0F"
      - "901417"
      - "961B1E"
      - "9B2226"
      - "9F2222"
      - "A3211E"
      - "A6211A"
      - "AA2016"
      - "AE2012"
      - "B42E0F"
      - "B93C0C"
      - "BF4B08"
      - "C45905"
      - "CA6702"
      - "BF7C27"
      - "B4924D"
      - "AAA772"
      - "9FBD98"
      - "94D2BD"
      - "78C5B5"
      - "5DB9AD"
      - "41ACA6"
      - "26A09E"
      - "198d98"
      - "008998"
      - "007d96"
      - "026b8d"
      - "00608a"
      - "005688"
      - "004c86"
      - "004284"
      - "003881"
      - "002d80"
      - "00227e"
      - "01177c"
      - "010b7b"
    label: "Anos desde o fogo"
    cmap_type: "sequential"
    unit: "anos"

  canopy_disturbance:
    name: "Distúrbio de Dossel"
    min: 0
    max: 12
    palette:
      - "505050"
      - "0D0A29"
      - "271258"
      - "491078"
      - "671B80"
      - "862781"
      - "A6317D"
      - "C53C74"
      - "E34E65"
      - "F66C5C"
      - "FC9065"
      - "FEB67C"
      - "FDDA9C"
    label: "Eventos de distúrbio"
    cmap_type: "categorical"
    discrete_labels:
      - "Não observado"
      - "1 evento"
      - "2 eventos"
      - "3 eventos"
      - "4 eventos"
      - "5 eventos"
      - "6 eventos"
      - "7 eventos"
      - "8 eventos"
      - "9 eventos"
      - "10 eventos"
      - "11 eventos"
      - "12 eventos"

  logging:
    name: "Corte Seletivo"
    min: 0
    max: 1
    palette:
      - "505050"
      - "e66101"
    label: "Corte seletivo"
    cmap_type: "categorical"
    discrete_labels:
      - "Não observado"
      - "Corte seletivo"

  natural_coverage:
    name: "Cobertura Natural"
    min: 0
    max: 2
    palette:
      - "505050"
      - "006400"
      - "b8af4e"
    label: "Cobertura natural"
    cmap_type: "categorical"
    discrete_labels:
      - "Não natural / Não observado"
      - "Floresta"
      - "Formação Natural Não-Florestal"
